### ISSUE TITLE
Navbar commands/icons are not clickable on mobile sometimes

### ISSUE THREAD

**Issue by karol-depka** [karol-depka/NetworkingMatcher#103]
==== ***Very high priority!!!*** ====

Navbar commands/icons are displayed correctly on mobile, but clicking on them often does not work.

Tested on samsung Galaxy A5 2017, today on version released on topicfriends.org.

On topicfriends.org/profile for example

Problem could be resulting from upgrade of material design and/or flexLayout which we did on ~February.

**Comment by zolastro** [comment]
Have been working on this and seems more of a performance issue (switching between tabs too fast). Also happens in desktop.

**Comment by zolastro** [comment]
The issue only appears to happen between the People & Topics pages (and Profile if the user is logged in). I've removed all logic from those modules and it works smoothly, so we can confirm that is a performance issue and not a problem with the navbar.

**Comment by karol-depka** [comment]
Hi David. So actually there is like two issues with similar symptoms.

1. what you probably mean: the app sometimes gets frozen while loading another page so the clicking on navbar have no immediate result

2. (what I mean in this issue here) - nothing is loading and the app is not frozen (you can verify that e.g. scrolling up and down a little bit and/or waiting to make sure everything is loaded. And then you can click and click on the navbar buttons and they do not react. THOUGH, perhaps the click goes through, to the html element underneath the navbar on the page. It is very important to investigate if the click goes to the element underneath the navbar, as one of the first troubleshooting steps.

**Comment by moi-j** [comment]
I've been looking around too and looks like the problem is related to TopicsService, with transformTags method in fact.
