### ISSUE TITLE
Add modal to Log in button

### ISSUE THREAD

**Issue by zolastro** [karol-depka/NetworkingMatcher#114]

**Comment by zolastro** [comment]
We would have to change all the modules structures, which is both error prone and not prioritary, so I'll saved the work done in a new branch: LoginModal

**Comment by moi-j** [comment]
Sorry, already done (I know I had no assignation but... I though I had)
Closed by:  f836cfd5853fb9203a70b0c7b1f2527d0c6a19e8

**Comment by zolastro** [comment]
Well, you did your work, so I can't see the problem ;)
