### ISSUE TITLE
Refresh user profile page on logout

### ISSUE THREAD

**Issue by zolastro** [karol-depka/NetworkingMatcher#116]

**Comment by moi-j** [comment]
Should we send the user to the homepage instead? wdyt?

**Comment by zolastro** [comment]
Good catch, easier implementation than what I did. Could you revert my last commit and do that instead?

**Comment by zolastro** [comment]
But what's the home page after all?

**Comment by moi-j** [comment]
Alex is doing it. It's suppose to be the topic searcher. I will implement the home page redirect as soon as we have the home page.
