### ISSUE TITLE
Translate to English: He leido y acepto la Política de Privacidad y tengo 16 años o más.

### ISSUE THREAD

**Issue by karol-depka** [karol-depka/NetworkingMatcher#138]
(for international users)

Also: "Por favor, marca la casilla..."

**Comment by karol-depka** [comment]
Closed? In which commit?

**Comment by AlejandroMN** [comment]
@AlejandroMornie
AlejandroMornie committed 10 minutes ago
1 parent abee1e6 commit e3f17911c2d5a002331a80f3e4479a24b4a40df4

**Comment by AlejandroMN** [comment]
Closed in commit e3f17911c2d5a002331a80f3e4479a24b4a40df4

**Comment by karol-depka** [comment]
Thanks.

Perhaps better to have the text also in Spanish for legal reasons?

--
Karol Depka Pradzinski
Software Developer && Entrepreneur
topicfriends.org/u/karol-depka
karoldepka.com/about
linkedin.com/in/karoldepka

**Comment by AlejandroMN** [comment]
Lets keep it in english until we create a full spanish version

**Comment by karol-depka** [comment]
Ok.

No legal requirement for Spanish?
Rgpd lopd?

--
Karol Depka Pradzinski
Software Developer && Entrepreneur
topicfriends.org/u/karol-depka
karoldepka.com/about
linkedin.com/in/karoldepka

**Comment by AlejandroMN** [comment]
Probably, the whole site should be available in spanish. Thats something we
should keep in mind.
Regards to RGPD didnt found any mention to language.
