### ISSUE TITLE
Change "Log In" to "Log In or Register" on buttons

### ISSUE THREAD

**Issue by karol-depka** [karol-depka/NetworkingMatcher#142]
Because some people say they don't know where to register.

We are so much ahead of the times that we don't need no stinky registration step :).

But that confuses people...

**Comment by zolastro** [comment]
I think it should  be named Sign Up, it's more common

**Comment by karol-depka** [comment]
Sign Up and Sign In?

I'm okay with this. As long as the users understands what is going on (that they don't need a distinct registration step).

Could/should add text "no registration required; just sign in!".
