### ISSUE TITLE
Disable two-finger browser zoom on mobile

### ISSUE THREAD

**Issue by karol-depka** [karol-depka/NetworkingMatcher#144]
At least on pages which have a map (so that map's own zoom would work).

**Comment by karol-depka** [comment]
@zolastro Thanks, Did the navbar problems (jumping, shifted, non-clickable) stop on mobile once the zoom was disabled?

**Comment by karol-depka** [comment]
@zolastro Is it still possible to zoom in/out on non-mobile browser?

**Comment by zolastro** [comment]
Yes, you can ;)
