### ISSUE TITLE
Fix broken pictures of People

### ISSUE THREAD

**Issue by karol-depka** [karol-depka/NetworkingMatcher#165]
When someone changes profile picture on Google (/ LinkedIn?) the pic becomes broken.

Options:
 - find a way to get up-to-date images urls
 - store images in Firebase

**Comment by karol-depka** [comment]
@hvitis Maybe You wanna tackle it someday, since You are already acquainted with Firebase login :).

**Comment by karol-depka** [comment]
First thing to do: show some generic profile picture if image fails to load (instead of browser's default image-failed-to-load picture)

**Comment by karol-depka** [comment]
potential starting point ```onerror="this.style.display='none'```

**Comment by hvitis** [comment]
Roger. Assign to me everything that you think may be done by a beginner.

**Comment by karol-depka** [comment]
Was done. Closing.
