### ISSUE TITLE
Update to newest Angular version

### ISSUE THREAD

**Issue by karol-depka** [karol-depka/NetworkingMatcher#4]
Consider first doing md- to mat- prefixes upgrade ( issue: https://github.com/karol-depka/NetworkingMatcher/issues/3 ), since:

"""Note: Running this tool with Angular Material versions higher than beta.11 will not work. The prefix updater tool requires type information from the outdated Md classes."""

-- https://www.npmjs.com/package/angular-material-prefix-updater

**Comment by karol-depka** [comment]
Maybe there is some automatic migration tool?

**Comment by karol-depka** [comment]
Also plz search for a migration guide if any.

**Comment by mjimenezmartin** [comment]
Try locking the version to the specific one **without ^**

**Comment by karol-depka** [comment]
So let's be pioneers and try 6.0.0-beta.3 (2018-02-07) :-).

If it causes problems, then:
1. Create StackOverflow question / GitHub issue
2. Work-around or ignore the issue for now (if not fatal)
3. If not possible, then plz do 5.x version (or 6.0.x another beta)

**Comment by karol-depka** [comment]
Moi and me, we haven't found breaking in 6.x changes on https://github.com/angular/angular/blob/master/CHANGELOG.md ...
Which seems too good to be true (especially in the light of Semantic Versioning).

Maybe we should take another look?
Maybe they did not call it "breaking changes" but something else in the text?
E.g. "incompatibilities" etc.

**Comment by karol-depka** [comment]
Please also pay close attention to the right/newest version of angular CLI.

**Comment by karol-depka** [comment]
If stuff gets weird with dependencies: consider removing node_modules and re-running npm install.

**Comment by karol-depka** [comment]
Aslo TypeScript version might have to be upgraded.

**Comment by mjimenezmartin** [comment]
Done by commit: 79f6bab23635815eee42831d333c0af82b43a8d4
