### ISSUE TITLE
Make the map location chooser dialog/modal bigger

### ISSUE THREAD

**Issue by karol-depka** [karol-depka/NetworkingMatcher#44]

**Comment by zolastro** [comment]
Do you want the actual modal bigger or just the map?

**Comment by karol-depka** [comment]
@zolastro You can experiment, for best UX :). 

Also, by-the-way you could try using another dialog/modal implementation, which would allow reuse of the map (since we had the slowdown after each time the map location picker was opened).
Candidates: primeng modal/dialog...

**Comment by karol-depka** [comment]
@zolastro if you find a nice combination but want to keep experimenting, then you can somehow keep it in the code; while maybe allowing user to switch using the /config

**Comment by zolastro** [comment]
@karol-depka Sure thing! :grinning:

**Comment by zolastro** [comment]
Done. Closing.
