### ISSUE TITLE
On topic details view: add a map with all the people with given topic interests / skills

### ISSUE THREAD

**Issue by karol-depka** [karol-depka/NetworkingMatcher#49]
e.g. topicfriends.org/topic/Angular

**Comment by karol-depka** [comment]
e.g. topicfriends.org/topic/Angular

**Comment by karol-depka** [comment]
Use the topic icon, if the topic has icon. If not, just display a user icon.
To consider: show user avatar icons?

**Comment by karol-depka** [comment]
Possible combo: show user avatars on the map, each user avatar with a "badge" of smaller topic icon.

**Comment by zolastro** [comment]
Already done
