### ISSUE TITLE
Fix firebase error (first error on console when loading app)

### ISSUE THREAD

**Issue by karol-depka** [karol-depka/NetworkingMatcher#72]
It is probably related to index.html and to LinkedIn log-in which uses Firebase SDK directly, instead of AngularFire.

**Comment by karol-depka** [comment]
The error is quite annoying and can lead to error-blindness; thus: high-priority to fix :).

**Comment by zolastro** [comment]
The problem was in NMWeb/src/index.html at line 43: 
`debugAlert('hello script in src/index.html, getFirebaseProjectId(): ' + getFirebaseProjectId());`

That line is called before firebase is initialized. I just commented that line out as a temporary fix.
