### ISSUE TITLE
Fix `6platform-browser.js:367 WARNING: sanitizing unsafe style value [object Object] (see http://g.co/ng/security#xss).`

### ISSUE THREAD

**Issue by karol-depka** [karol-depka/NetworkingMatcher#74]
It appears on the console. E.g. on `http://localhost:4444/profile`

**Comment by zolastro** [comment]
Seems to be a problem with the use of `[style.xs]` with flex-layout. The problem is fixed if `[ngStyle.xs]` is used instead. Check https://github.com/angular/flex-layout/issues/514 for further information.
