### ISSUE TITLE
Improve skill levels popup modal on small screens

### ISSUE THREAD

**Issue by karol-depka** [karol-depka/NetworkingMatcher#86]
<img width="350" alt="bildschirmfoto 2018-03-23 um 17 30 1" src="https://user-images.githubusercontent.com/958486/37841420-023866f4-2ec0-11e8-8f0c-8912b8027437.png">

Can we make the popup dialog almost-full-screen ?

**Comment by moi-j** [comment]
Fixed through commit 7cc25be
